### ISSUE TITLE
Redesign and responsive footer

### ISSUE THREAD

**Issue by R1MO9** [codervivek5/VigyBag#993] opened 2024-05-11 02:38 UTC
I can create a better responsive footer for this and allow me to do this

**Comment by R1MO9** [comment] 2024-05-11 02:38
Assign this to me
under GSSOC'24

**Comment by aditya7483thakur** [comment] 2024-05-11 04:44
Hello Sir ! can you assign this issue to me

**Comment by codervivek5** [comment] 2024-05-11 06:15
@R1MO9 can you share any over view or sample of UI so that I can understand what exactly want to make changes

**Comment by kamalesh-og** [comment] 2024-05-11 06:54
Hello @codervivek5 ,
I am one of the contributors to GSSOC'24, and I would like to work on this issue "Redesign and responsive footer"
![image](https://github.com/codervivek5/VigyBag/assets/163159351/58b28a98-3e32-4aa8-8391-8f23f318f778)

I have experience in Web Development and want to contribute to projects in open source, and have solved these kinds of issues prior, and ready to learn and make appropriate changes to enhance your project.
I would like to make the Footer section more organised and formatted, I can judge the colour gradient used from the other sections and more precisely from the **Contact Us** Section, so i can work further in CSS and make the adjustments

Can you please assign this issue to me!?
Thank You.

**Comment by codervivek5** [comment] 2024-05-11 06:57
kindly share any UI so that i can understand what you guys want to chnge

**Comment by kamalesh-og** [comment] 2024-05-11 06:58
I have included the screenshot in my request, Footer Section of Contact Us

**Comment by codervivek5** [comment] 2024-05-11 07:01
> I have included the screenshot in my request, Footer Section of Contact Us

@kamalesh-og I am saying that what will you improve ? have you any image from google or drabbble ?

**Comment by R1MO9** [comment] 2024-05-11 07:20
> @R1MO9 can you share any over view or sample of UI so that I can understand what exactly want to make changes

![image](https://github.com/codervivek5/VigyBag/assets/118689102/c6aa4499-cb4c-4f20-bb84-960ce4c04370)
something like this or you can also provide anykind of desired footer you want

**Comment by kamalesh-og** [comment] 2024-05-11 07:28
yes exactly
![image](https://github.com/codervivek5/VigyBag/assets/163159351/b41202b6-fbea-4947-b5eb-813f704ef7c1)
even the one said by @R1MO9 can also be done

> > I have included the screenshot in my request, Footer Section of Contact Us
> 
> @kamalesh-og I am saying that what will you improve ? have you any image from google or drabbble ?

**Comment by codervivek5** [comment] 2024-05-12 04:13
@R1MO9 just go home page and use that footer ... that is more attaractive then this

**Comment by kamalesh-og** [comment] 2024-05-12 04:51
![image](https://github.com/codervivek5/VigyBag/assets/163159351/6545138b-82ee-496b-a25d-f3b2249f52fb)
@codervivek5 Yeah will do, can you assign me for this?

**Comment by R1MO9** [comment] 2024-05-12 04:59
@codervivek5 ok.. assign and add labels

**Comment by varshithar12** [comment] 2024-05-15 08:30
I would like to work on this issue.
Please Assign me this task.

**Comment by kamalesh-og** [comment] 2024-05-15 15:09
> @codervivek5 ok.. assign and add labels

Yeah Thank you, Ill complete by 17th

**Comment by codervivek5** [comment] 2024-05-20 16:30
what is the issue is occurred ... just explain

**Closed as completed** 2024-05-21 12:04 UTC
